<a href="https://colab.research.google.com/github/vinoda3827/editREADME/blob/main/imdb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [ ]:
pip install numpy

In [2]:
import pandas as pd
import numpy as np

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
df=pd.read_csv(r'/content/drive/MyDrive/imdb_data.csv')

In [12]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [13]:
columns_to_keep= ['budget', 'genres','original_language', 'original_title','cast', 'crew', 'revenue']

In [15]:
def convert_to_lst(string):
    try:
        return eval(string)
    except:
        return np.nan

In [16]:
convert_to_lst(np.nan)

nan

In [18]:
df['genres']=df['genres'].apply(convert_to_lst)
df['crew']=df['crew'].apply(convert_to_lst)
df['cast']=df['cast'].apply(convert_to_lst)

In [19]:
df1=df.copy()

# **`Q1`**

In [21]:
df1['profit']=df1['revenue']-df1['budget']
max_profit=df1['profit'].max()
df2_max=df1[df1['profit']==max_profit].reset_index(drop=True)
df2_max['crew'][0]

[{'credit_id': '52fe4cc8c3a36847f823e681',
  'department': 'Production',
  'gender': 2,
  'id': 12835,
  'job': 'Producer',
  'name': 'Vin Diesel',
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e687',
  'department': 'Production',
  'gender': 2,
  'id': 11874,
  'job': 'Producer',
  'name': 'Neal H. Moritz',
  'profile_path': '/cNcsEYmoS4niCz3UkVAA09dUIob.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e68d',
  'department': 'Writing',
  'gender': 2,
  'id': 58191,
  'job': 'Writer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e693',
  'department': 'Writing',
  'gender': 0,
  'id': 8162,
  'job': 'Characters',
  'name': 'Gary Scott Thompson',
  'profile_path': '/e2dMfqFvRsOXgWZ1VToYLmos17y.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e699',
  'department': 'Directing',
  'gender': 2,
  'id': 2127,
  'job': 'Director',
  'name': 'James Wan',
  'profile_path': '/d1LSKfzi5J6QngWS7niN1zPJdud.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e6a7',
  'department': 'Camera',
  'gender': 2,
  'id': 58192,
  'job': 'Director of Photography',
  'name': 'Stephen F. Windon',
  'profile_path': None},
 {'credit_id': '5534714692514125dc002be4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1455610,
  'job': 'Animation',
  'name': 'Tony Mecca',
  'profile_path': None},
 {'credit_id': '554fa7b992514110bd002a9d',
  'department': 'Camera',
  'gender': 0,
  'id': 1421687,
  'job': 'Director of Photography',
  'name': 'Marc Spicer',
  'profile_path': None},
 {'credit_id': '554fa7cbc3a36822540047fd',
  'department': 'Production',
  'gender': 1,
  'id': 90635,
  'job': 'Executive Producer',
  'name': 'Samantha Vincent',
  'profile_path': None},
 {'credit_id': '554fa7d89251413fcf00773d',
  'department': 'Production',
  'gender': 0,
  'id': 84064,
  'job': 'Associate Producer',
  'name': 'F. Valentino Morales',
  'profile_path': '/w85eCnNP0VgmfV5NWyq2SvRGi2y.jpg'},
 {'credit_id': '554fa7f2c3a3682254004803',
  'department': 'Production',
  'gender': 2,
  'id': 8181,
  'job': 'Producer',
  'name': 'Michael Fottrell',
  'profile_path': None},
 {'credit_id': '554fa80292514110bd002aa8',
  'department': 'Production',
  'gender': 0,
  'id': 75826,
  'job': 'Producer',
  'name': 'Brandon Birtell',
  'profile_path': None},
 {'credit_id': '55ed993ac3a3682c62015607',
  'department': 'Editing',
  'gender': 0,
  'id': 1204244,
  'job': 'Editor',
  'name': 'Leigh Folsom Boyd',
  'profile_path': None},
 {'credit_id': '55ed994cc3a3687d3b00d64c',
  'department': 'Editing',
  'gender': 0,
  'id': 1204245,
  'job': 'Editor',
  'name': 'Dylan Highsmith',
  'profile_path': None},
 {'credit_id': '55ed995dc3a3682c5d016867',
  'department': 'Editing',
  'gender': 0,
  'id': 62813,
  'job': 'Editor',
  'name': 'Kirk M. Morri',
  'profile_path': None},
 {'credit_id': '55ed99739251413e41014641',
  'department': 'Editing',
  'gender': 2,
  'id': 6668,
  'job': 'Editor',
  'name': 'Christian Wagner',
  'profile_path': None},
 {'credit_id': '55ed99859251413e3a014aae',
  'department': 'Production',
  'gender': 1,
  'id': 9545,
  'job': 'Casting',
  'name': 'Anne McCarthy',
  'profile_path': None},
 {'credit_id': '55ed99a4c3a3682c5d016875',
  'department': 'Production',
  'gender': 0,
  'id': 1276602,
  'job': 'Casting',
  'name': 'Kellie Roy',
  'profile_path': None},
 {'credit_id': '55ed99c7c3a3682c5d01687e',
  'department': 'Art',
  'gender': 0,
  'id': 1445830,
  'job': 'Art Direction',
  'name': 'Jonathan Carlos',
  'profile_path': None},
 {'credit_id': '55ed99d89251413e32014a65',
  'department': 'Art',
  'gender': 2,
  'id': 62780,
  'job': 'Art Direction',
  'name': 'Alan Hook',
  'profile_path': None},
 {'credit_id': '55ed99e992514106d600d85e',
  'department': 'Art',
  'gender': 0,
  'id': 1493864,
  'job': 'Art Direction',
  'name': 'Jay Pelissier',
  'profile_path': None},
 {'credit_id': '55ed9a36c3a3682c700147e3',
  'department': 'Art',
  'gender': 1,
  'id': 1506359,
  'job': 'Art Department Coordinator',
  'name': 'Kelly Richardson',
  'profile_path': None},
 {'credit_id': '55ed9a52c3a3682c640130c3',
  'department': 'Art',
  'gender': 0,
  'id': 1506360,
  'job': 'Art Department Coordinator',
  'name': 'Courtney Cocherell',
  'profile_path': None},
 {'credit_id': '55ed9a6cc3a368090c004f9c',
  'department': 'Art',
  'gender': 0,
  'id': 1326651,
  'job': 'Assistant Art Director',
  'name': 'Elena Albanese',
  'profile_path': None},
 {'credit_id': '55ed9a96c3a3686f17003be1',
  'department': 'Art',
  'gender': 0,
  'id': 1405376,
  'job': 'Assistant Art Director',
  'name': 'Alex McCarroll',
  'profile_path': None},
 {'credit_id': '55ed9acbc3a3682c640130e4',
  'department': 'Art',
  'gender': 0,
  'id': 1338147,
  'job': 'Construction Coordinator',
  'name': 'Bruce Di Valerio',
  'profile_path': None},
 {'credit_id': '55ed9b03c3a3682c640130f5',
  'department': 'Art',
  'gender': 2,
  'id': 52600,
  'job': 'Production Design',
  'name': 'Bill Brzeski',
  'profile_path': None},
 {'credit_id': '55ed9b169251413e2f0145a8',
  'department': 'Art',
  'gender': 1,
  'id': 75391,
  'job': 'Set Decoration',
  'name': 'Danielle Berman',
  'profile_path': None},
 {'credit_id': '55ed9b29c3a3682c5d0168d9',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 2519,
  'job': 'Costume Design',
  'name': 'Sanja Milkovic Hays',
  'profile_path': None},
 {'credit_id': '55ed9bdac3a3682c62015698',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1439109,
  'job': 'Costume Supervisor',
  'name': 'Nava R. Sadan',
  'profile_path': None},
 {'credit_id': '55ed9c0bc3a3686f17003c45',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1439747,
  'job': 'Costume Supervisor',
  'name': 'Andrew Hunt',
  'profile_path': None},
 {'credit_id': '55ed9c3192514106d600d8e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506364,
  'job': 'Set Costumer',
  'name': 'Jim Alan Cook',
  'profile_path': None},
 {'credit_id': '55ed9c45c3a3682c5d016925',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1415019,
  'job': 'Set Costumer',
  'name': 'Shayne Allen Duhon',
  'profile_path': None},
 {'credit_id': '55ed9c579251413e32014af5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506365,
  'job': 'Set Costumer',
  'name': 'Empress Holley',
  'profile_path': None},
 {'credit_id': '55ed9c6d9251413e450148ff',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1413125,
  'job': 'Set Costumer',
  'name': 'Marina Marit',
  'profile_path': None},
 {'credit_id': '55ed9c8d92514106d600d8fb',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506366,
  'job': 'Set Costumer',
  'name': 'Les Morgan',
  'profile_path': None},
 {'credit_id': '55ed9cda9251413e2f014612',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1408293,
  'job': 'Hairstylist',
  'name': 'Linda D. Flowers',
  'profile_path': None},
 {'credit_id': '55ed9cf69251413e2f01461d',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1412767,
  'job': 'Hairstylist',
  'name': "Yesim 'Shimmy' Osman",
  'profile_path': None},
 {'credit_id': '55ed9d0ec3a3687d3b00d73a',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506367,
  'job': 'Hairstylist',
  'name': 'Jennifer Santiago',
  'profile_path': None},
 {'credit_id': '55ed9d2a9251413e3e0155d8',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1425409,
  'job': 'Hairstylist',
  'name': 'Rachel Solow',
  'profile_path': None},
 {'credit_id': '55ed9d4cc3a3682c620156ed',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1452643,
  'job': 'Hairstylist',
  'name': 'Roxane Griffin',
  'profile_path': None},
 {'credit_id': '55ed9d6fc3a3682c5d01696f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1309209,
  'job': 'Makeup Department Head',
  'name': 'James MacKinnon',
  'profile_path': None},
 {'credit_id': '55ed9d8cc3a368090c00504f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506368,
  'job': 'Makeup Artist',
  'name': 'Autumn Butler',
  'profile_path': None},
 {'credit_id': '55ed9da09251413e3a014b98',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1437798,
  'job': 'Makeup Artist',
  'name': "Roxy D'Alonzo",
  'profile_path': None},
 {'credit_id': '55ed9db79251413e3a014ba5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506369,
  'job': 'Makeup Artist',
  'name': 'Hee Soo Kwon',
  'profile_path': None},
 {'credit_id': '55ed9dce9251413e32014b4e',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1459196,
  'job': 'Makeup Artist',
  'name': 'Sarah Mays',
  'profile_path': None},
 {'credit_id': '55ed9de4c3a3687d3b00d775',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 15330,
  'job': 'Makeup Artist',
  'name': 'Paul Pattison',
  'profile_path': None},
 {'credit_id': '55ed9df99251413e3e015610',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1317667,
  'job': 'Makeup Artist',
  'name': 'Eleanor Sabaduquia',
  'profile_path': None},
 {'credit_id': '55ed9e1fc3a3687d3b00d77e',
  'department': 'Crew',
  'gender': 0,
  'id': 1414497,
  'job': 'Property Master',
  'name': 'Guillaume DeLouche',
  'profile_path': None},
 {'credit_id': '55ed9e3ac3a368090c005084',
  'department': 'Crew',
  'gender': 0,
  'id': 1464516,
  'job': 'Property Master',
  'name': 'Douglas T. Madison',
  'profile_path': None},
 {'credit_id': '55ed9f5d9251413e3e015662',
  'department': 'Crew',
  'gender': 2,
  'id': 57158,
  'job': 'Second Unit Cinematographer',
  'name': 'Igor Meglic',
  'profile_path': None},
 {'credit_id': '55ed9fa0c3a3682c6401320f',
  'department': 'Crew',
  'gender': 0,
  'id': 13670,
  'job': 'Second Unit Cinematographer',
  'name': 'Jacques Haitkin',
  'profile_path': None},
 {'credit_id': '55ed9fc59251413e32014bbc',
  'department': 'Lighting',
  'gender': 0,
  'id': 1437304,
  'job': 'Gaffer',
  'name': 'Michael Ambrose',
  'profile_path': None},
 {'credit_id': '55ed9fe79251413e410147e4',
  'department': 'Camera',
  'gender': 0,
  'id': 1506371,
  'job': 'Camera Operator',
  'name': 'Denise Bailie',
  'profile_path': None},
 {'credit_id': '55ed9ffa9251413e3a014c40',
  'department': 'Camera',
  'gender': 0,
  'id': 1506373,
  'job': 'Camera Operator',
  'name': 'Robert-James Bova',
  'profile_path': None},
 {'credit_id': '55eda0299251413e3a014c49',
  'department': 'Lighting',
  'gender': 0,
  'id': 1439108,
  'job': 'Rigging Gaffer',
  'name': 'Tom Fendley',
  'profile_path': None},
 {'credit_id': '55eda056c3a3682c7001494b',
  'department': 'Camera',
  'gender': 0,
  'id': 1434896,
  'job': 'Camera Operator',
  'name': 'Sarah Levy',
  'profile_path': None},
 {'credit_id': '55eda06e9251413e450149ee',
  'department': 'Camera',
  'gender': 2,
  'id': 74989,
  'job': 'Camera Operator',
  'name': 'Mark Emery Moore',
  'profile_path': '/mhjX0FuAXv6SeSLLFHpaaiQbx6P.jpg'},
 {'credit_id': '55eda082c3a3682c6b014009',
  'department': 'Camera',
  'gender': 2,
  'id': 1432918,
  'job': 'Camera Operator',
  'name': 'Daniel Nichols',
  'profile_path': None},
 {'credit_id': '55eda09d9251413e3e01569d',
  'department': 'Camera',
  'gender': 0,
  'id': 1439104,
  'job': 'Camera Operator',
  'name': 'Onofrio Nino Pansini',
  'profile_path': None},
 {'credit_id': '55eda0b59251413e3a014c6c',
  'department': 'Camera',
  'gender': 0,
  'id': 1408356,
  'job': 'Camera Operator',
  'name': 'David Richert',
  'profile_path': None},
 {'credit_id': '55eda0d1c3a3686f17003d58',
  'department': 'Camera',
  'gender': 2,
  'id': 1411271,
  'job': 'Camera Operator',
  'name': 'Michael J. Walker',
  'profile_path': None},
 {'credit_id': '55eda0f7c3a3687d3b00d81b',
  'department': 'Camera',
  'gender': 2,
  'id': 1378241,
  'job': 'Camera Operator',
  'name': 'Maurice K. McGuire',
  'profile_path': None},
 {'credit_id': '55eda1159251413e3e0156bd',
  'department': 'Camera',
  'gender': 0,
  'id': 1411842,
  'job': 'Camera Operator',
  'name': 'Richard Latham',
  'profile_path': None},
 {'credit_id': '55eda12c92514106d600da0a',
  'department': 'Camera',
  'gender': 0,
  'id': 1404739,
  'job': 'Helicopter Camera',
  'name': 'Steve Koster',
  'profile_path': None},
 {'credit_id': '55eda1939251413e3501498d',
  'department': 'Camera',
  'gender': 0,
  'id': 91122,
  'job': 'Helicopter Camera',
  'name': 'Dylan Goss',
  'profile_path': None},
 {'credit_id': '55eda1b39251413e3a014ca8',
  'department': 'Camera',
  'gender': 0,
  'id': 82169,
  'job': 'Steadicam Operator',
  'name': 'Geoffrey Haley',
  'profile_path': None},
 {'credit_id': '55eda1c7c3a3686f17003d8c',
  'department': 'Camera',
  'gender': 0,
  'id': 1419105,
  'job': 'Still Photographer',
  'name': 'Scott Garfield',
  'profile_path': None},
 {'credit_id': '55eda1dbc3a3686f17003d92',
  'department': 'Camera',
  'gender': 2,
  'id': 1395281,
  'job': 'Additional Camera',
  'name': 'Bob Gorelick',
  'profile_path': None},
 {'credit_id': '55eda200c3a3682c5d016a8f',
  'department': 'Camera',
  'gender': 0,
  'id': 1375920,
  'job': 'Additional Camera',
  'name': 'J. Christopher Campbell',
  'profile_path': None},
 {'credit_id': '55eda228c3a3682c64013295',
  'department': 'Lighting',
  'gender': 0,
  'id': 1403412,
  'job': 'Gaffer',
  'name': 'Dan Cornwall',
  'profile_path': None},
 {'credit_id': '55eda25f92514106d600da4b',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1442137,
  'job': 'Animation Supervisor',
  'name': 'Catherine Mullan',
  'profile_path': None},
 {'credit_id': '55eda292c3a3682c5d016ab2',
  'department': 'Sound',
  'gender': 0,
  'id': 1393405,
  'job': 'Music Editor',
  'name': 'Robb Boyd',
  'profile_path': None},
 {'credit_id': '55eda2a9c3a3682c6b014075',
  'department': 'Sound',
  'gender': 0,
  'id': 1328758,
  'job': 'Music Editor',
  'name': 'Matthew Llewellyn',
  'profile_path': None},
 {'credit_id': '55eda2c89251413e45014a6d',
  'department': 'Directing',
  'gender': 0,
  'id': 1389138,
  'job': 'Script Supervisor',
  'name': 'Jody Blose',
  'profile_path': None},
 {'credit_id': '55eda305c3a3682c700149c1',
  'department': 'Directing',
  'gender': 0,
  'id': 1408365,
  'job': 'Script Supervisor',
  'name': 'Brenda K. Wachel',
  'profile_path': None},
 {'credit_id': '55eda32dc3a3686f17003ddd',
  'department': 'Crew',
  'gender': 2,
  'id': 8167,
  'job': 'Thanks',
  'name': 'Paul Walker',
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'credit_id': '55eda3b592514106d600da94',
  'department': 'Editing',
  'gender': 0,
  'id': 1400354,
  'job': 'Digital Intermediate',
  'name': 'Amy Pawlowski',
  'profile_path': None},
 {'credit_id': '55eda3d792514106d600da9b',
  'department': 'Editing',
  'gender': 0,
  'id': 110262,
  'job': 'First Assistant Editor',
  'name': 'Richard Conkling',
  'profile_path': None},
 {'credit_id': '55eda3edc3a3686f17003e0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1194885,
  'job': 'First Assistant Editor',
  'name': 'Dave  Cory',
  'profile_path': None},
 {'credit_id': '55eda4169251413e410148ec',
  'department': 'Editing',
  'gender': 0,
  'id': 1439749,
  'job': 'First Assistant Editor',
  'name': 'Laura Steiger',
  'profile_path': None},
 {'credit_id': '55eda48092514106d600daba',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1506377,
  'job': 'Animation Supervisor',
  'name': 'Daniel Barrett',
  'profile_path': '/pplTJP3gCWmP3SMDrXjOt1579MV.jpg'},
 {'credit_id': '55eda5109251413e32014cf0',
  'department': 'Sound',
  'gender': 0,
  'id': 12562,
  'job': 'ADR & Dubbing',
  'name': 'Anna MacKenzie',
  'profile_path': None},
 {'credit_id': '55eda51ac3a3686f17003e52',
  'department': 'Editing',
  'gender': 0,
  'id': 12562,
  'job': 'Dialogue Editor',
  'name': 'Anna MacKenzie',
  'profile_path': None},
 {'credit_id': '55eda539c3a368090c0051c2',
  'department': 'Editing',
  'gender': 0,
  'id': 1342658,
  'job': 'Dialogue Editor',
  'name': 'Frederick H. Stahly',
  'profile_path': None},
 {'credit_id': '55eda56a9251413e45014adf',
  'department': 'Sound',
  'gender': 2,
  'id': 1077782,
  'job': 'Foley',
  'name': 'Gary A. Hecker',
  'profile_path': '/qyBUauN3XIS2Mlus3OdGCmrUo0S.jpg'},
 {'credit_id': '55eda58292514106d600daf4',
  'department': 'Sound',
  'gender': 0,
  'id': 1367362,
  'job': 'Foley',
  'name': 'Rick Owens',
  'profile_path': None},
 {'credit_id': '55eda59ac3a3682c5d016b50',
  'department': 'Sound',
  'gender': 0,
  'id': 1236340,
  'job': 'Foley',
  'name': 'Dylan Tuomy-Wilhoit',
  'profile_path': None},
 {'credit_id': '55eda5b09251413e45014af1',
  'department': 'Sound',
  'gender': 0,
  'id': 548445,
  'job': 'Foley',
  'name': 'Jeffrey Wilhoit',
  'profile_path': None},
 {'credit_id': '55eda7169251413e45014b3b',
  'department': 'Sound',
  'gender': 2,
  'id': 7239,
  'job': 'Sound Designer',
  'name': 'Peter Brown',
  'profile_path': None},
 {'credit_id': '55eda73d9251413e4101498c',
  'department': 'Sound',
  'gender': 0,
  'id': 1392083,
  'job': 'Sound Designer',
  'name': 'Ann Scibelli',
  'profile_path': None},
 {'credit_id': '55eda779c3a3682c70014abc',
  'department': 'Sound',
  'gender': 0,
  'id': 1413453,
  'job': 'Sound Effects Editor',
  'name': 'Stephen P. Robinson',
  'profile_path': None},
 {'credit_id': '55eda7989251413e3e015838',
  'department': 'Sound',
  'gender': 0,
  'id': 1394131,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Jon Taylor',
  'profile_path': None},
 {'credit_id': '55eda7afc3a3686f17003ebf',
  'department': 'Sound',
  'gender': 0,
  'id': 1394130,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Frank A. Monta√±o',
  'profile_path': None},
 {'credit_id': '55eda7d79251413e32014e11',
  'department': 'Sound',
  'gender': 0,
  'id': 1309884,
  'job': 'Supervising Sound Editor',
  'name': 'Joe Dzuban',
  'profile_path': None},
 {'credit_id': '570bd40dc3a36802a30002d9',
  'department': 'Art',
  'gender': 0,
  'id': 1424153,
  'job': 'Supervising Art Director',
  'name': 'Desma Murphy',
  'profile_path': None},
 {'credit_id': '5668cc7a92514174040040f2',
  'department': 'Sound',
  'gender': 2,
  'id': 6041,
  'job': 'Original Music Composer',
  'name': 'Brian Tyler',
  'profile_path': '/22QWiNJj03amY6GT1QPUs7dbdcB.jpg'},
 {'credit_id': '58ebe1fa925141281008e943',
  'department': 'Production',
  'gender': 2,
  'id': 58191,
  'job': 'Executive Producer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'}]

In [22]:
for i in df2_max['crew'][0]:
    if i["job"] == "Producer" or i["job"] == "Director":
        print(f'{i["job"]}:{i["name"]}')

Producer:Vin Diesel
Producer:Neal H. Moritz
Director:James Wan
Producer:Michael Fottrell
Producer:Brandon Birtell

In [23]:
df2_max['cast'].iloc[0]

[{'cast_id': 17,
  'character': 'Dominic Toretto',
  'credit_id': '5431dfd10e0a265915002c34',
  'gender': 2,
  'id': 12835,
  'name': 'Vin Diesel',
  'order': 0,
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'cast_id': 19,
  'character': "Brian O'Conner",
  'credit_id': '5431dfe4c3a3681143002b98',
  'gender': 2,
  'id': 8167,
  'name': 'Paul Walker',
  'order': 1,
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'cast_id': 18,
  'character': 'Hobbs',
  'credit_id': '5431dfdbc3a36831a6004376',
  'gender': 2,
  'id': 18918,
  'name': 'Dwayne Johnson',
  'order': 2,
  'profile_path': '/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg'},
 {'cast_id': 20,
  'character': 'Letty',
  'credit_id': '5431dfeec3a36811ef002c75',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 3,
  'profile_path': '/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg'},
 {'cast_id': 28,
  'character': 'Roman',
  'credit_id': '5431e0310e0a2656e2002c95',
  'gender': 2,
  'id': 8169,
  'name': 'Tyrese Gibson',
  'order': 4,
  'profile_path': '/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg'},
 {'cast_id': 31,
  'character': "Tej (as Chris 'Ludacris' Bridges)",
  'credit_id': '5431e0520e0a2658b2002c3c',
  'gender': 2,
  'id': 8171,
  'name': 'Ludacris',
  'order': 5,
  'profile_path': '/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg'},
 {'cast_id': 24,
  'character': 'Mia',
  'credit_id': '5431e00dc3a36811ef002c7e',
  'gender': 1,
  'id': 22123,
  'name': 'Jordana Brewster',
  'order': 6,
  'profile_path': '/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg'},
 {'cast_id': 25,
  'character': 'Jakande',
  'credit_id': '5431e015c3a36831a90040da',
  'gender': 2,
  'id': 938,
  'name': 'Djimon Hounsou',
  'order': 7,
  'profile_path': '/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg'},
 {'cast_id': 30,
  'character': 'Kiet',
  'credit_id': '5431e04a0e0a26464300432c',
  'gender': 2,
  'id': 57207,
  'name': 'Tony Jaa',
  'order': 8,
  'profile_path': '/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg'},
 {'cast_id': 21,
  'character': 'Kara',
  'credit_id': '5431dff40e0a2646490043fa',
  'gender': 0,
  'id': 997887,
  'name': 'Ronda Rousey',
  'order': 9,
  'profile_path': '/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg'},
 {'cast_id': 27,
  'character': 'Ramsey',
  'credit_id': '5431e026c3a36831ac004333',
  'gender': 1,
  'id': 1251069,
  'name': 'Nathalie Emmanuel',
  'order': 10,
  'profile_path': '/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg'},
 {'cast_id': 22,
  'character': 'Mr. Nobody',
  'credit_id': '5431dffa0e0a265872002bdf',
  'gender': 2,
  'id': 6856,
  'name': 'Kurt Russell',
  'order': 11,
  'profile_path': '/rlnFuNkisPpuypARI7QaGCmOY6V.jpg'},
 {'cast_id': 16,
  'character': 'Deckard Shaw',
  'credit_id': '5431dfc70e0a265872002bd5',
  'gender': 2,
  'id': 976,
  'name': 'Jason Statham',
  'order': 12,
  'profile_path': '/PhWiWgasncGWD9LdbsGcmxkV4r.jpg'},
 {'cast_id': 39,
  'character': 'Han',
  'credit_id': '554fa75f92514110bd002a7d',
  'gender': 2,
  'id': 61697,
  'name': 'Sung Kang',
  'order': 13,
  'profile_path': '/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg'},
 {'cast_id': 38,
  'character': 'Gisele',
  'credit_id': '554fa7439251413e40005aa1',
  'gender': 1,
  'id': 90633,
  'name': 'Gal Gadot',
  'order': 14,
  'profile_path': '/34kHAyBaBhq2kUrmhM15paEBuuI.jpg'},
 {'cast_id': 15,
  'character': 'Sean Boswell',
  'credit_id': '5431dfbb0e0a265915002c2d',
  'gender': 2,
  'id': 155,
  'name': 'Lucas Black',
  'order': 15,
  'profile_path': '/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg'},
 {'cast_id': 23,
  'character': 'Elena',
  'credit_id': '5431e003c3a36811ef002c7c',
  'gender': 1,
  'id': 73269,
  'name': 'Elsa Pataky',
  'order': 16,
  'profile_path': '/c1km2kqasJT9GTISMbBZpp3jbuR.jpg'},
 {'cast_id': 35,
  'character': 'Hector',
  'credit_id': '554fa677c3a3687b7d002468',
  'gender': 2,
  'id': 53252,
  'name': 'Noel Gugliemi',
  'order': 17,
  'profile_path': '/mI5urNyZJAzIGxelTjBkm624DkB.jpg'},
 {'cast_id': 37,
  'character': 'Sheppard',
  'credit_id': '554fa6f19251413ea10004fc',
  'gender': 2,
  'id': 222906,
  'name': 'John Brotherton',
  'order': 18,
  'profile_path': '/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg'},
 {'cast_id': 34,
  'character': 'Owen Shaw',
  'credit_id': '554fa651c3a3681870005275',
  'gender': 2,
  'id': 114019,
  'name': 'Luke Evans',
  'order': 19,
  'profile_path': '/1d31uDYub8TaLOPWfgX78OotduD.jpg'},
 {'cast_id': 36,
  'character': 'Safar',
  'credit_id': '554fa6d7c3a3685221000283',
  'gender': 2,
  'id': 492791,
  'name': 'Ali Fazal',
  'order': 20,
  'profile_path': '/AmT132VCz3InJBAQQPJnqqgsQsB.jpg'},
 {'cast_id': 145,
  'character': 'Jack',
  'credit_id': '59a8b72092514157c601fb92',
  'gender': 0,
  'id': 1880145,
  'name': 'Miller Kimsey',
  'order': 21,
  'profile_path': None},
 {'cast_id': 146,
  'character': 'Jack',
  'credit_id': '59a8b72b925141579d020797',
  'gender': 0,
  'id': 1880146,
  'name': 'Charlie Kimsey',
  'order': 22,
  'profile_path': None},
 {'cast_id': 133,
  'character': 'Samantha Hobbs',
  'credit_id': '56417cfec3a3685be2001846',
  'gender': 1,
  'id': 1533850,
  'name': 'Eden Estrella',
  'order': 23,
  'profile_path': '/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg'},
 {'cast_id': 147,
  'character': 'Letty Fan',
  'credit_id': '59a8b787c3a36874d5007d12',
  'gender': 2,
  'id': 1534800,
  'name': 'Gentry White',
  'order': 24,
  'profile_path': '/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg'},
 {'cast_id': 26,
  'character': 'Female Racer',
  'credit_id': '5431e01c0e0a265834002c97',
  'gender': 1,
  'id': 1364893,
  'name': 'Iggy Azalea',
  'order': 25,
  'profile_path': '/KG5skDx5WeGDijkUUQnmOP0crG.jpg'},
 {'cast_id': 148,
  'character': 'Male Racer',
  'credit_id': '59a8b7afc3a3683d0701b1ad',
  'gender': 0,
  'id': 1161711,
  'name': 'Jon Lee Brody',
  'order': 26,
  'profile_path': '/u1agQE1nYgt2LOijksYJMPYxpKh.jpg'},
 {'cast_id': 135,
  'character': 'Race Starter',
  'credit_id': '56c259c89251414a9b000865',
  'gender': 1,
  'id': 1578220,
  'name': 'Levy Tran',
  'order': 27,
  'profile_path': '/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg'},
 {'cast_id': 132,
  'character': 'Hot Teacher',
  'credit_id': '56417cc592514128af001862',
  'gender': 0,
  'id': 118593,
  'name': 'Anna Colwell',
  'order': 28,
  'profile_path': '/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg'},
 {'cast_id': 149,
  'character': 'Doctor',
  'credit_id': '59a8b80e92514157ab0206fc',
  'gender': 0,
  'id': 1880147,
  'name': 'Viktor Hernandez',
  'order': 29,
  'profile_path': None},
 {'cast_id': 150,
  'character': 'Priest',
  'credit_id': '59a8b84092514157c601fce8',
  'gender': 2,
  'id': 80619,
  'name': 'Steve Coulter',
  'order': 30,
  'profile_path': '/v1cwS9Ia89pO154Wje3m4IxuI3.jpg'},
 {'cast_id': 130,
  'character': 'Merc Tech',
  'credit_id': '56417c3092514128a6001a15',
  'gender': 0,
  'id': 97844,
  'name': 'Robert Pralgo',
  'order': 31,
  'profile_path': '/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg'},
 {'cast_id': 151,
  'character': 'Weapons Tech',
  'credit_id': '59a8b888c3a3683ce601e3aa',
  'gender': 0,
  'id': 1381712,
  'name': 'Antwan Mills',
  'order': 32,
  'profile_path': '/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg'},
 {'cast_id': 152,
  'character': 'Billionaire',
  'credit_id': '59a8b8bac3a36874d5007ea3',
  'gender': 0,
  'id': 1880148,
  'name': 'J.J. Phillips',
  'order': 33,
  'profile_path': None},
 {'cast_id': 153,
  'character': 'Dominican Priest',
  'credit_id': '59a8b8ccc3a3683c8701fa73',
  'gender': 0,
  'id': 1880149,
  'name': 'Jorge Ferragut',
  'order': 34,
  'profile_path': None},
 {'cast_id': 154,
  'character': 'Hana',
  'credit_id': '59a8b8e3c3a36874d5007ec7',
  'gender': 0,
  'id': 1440699,
  'name': 'Sara Sohn',
  'order': 35,
  'profile_path': '/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg'},
 {'cast_id': 155,
  'character': 'Merc Driver (as Ben Blankenship)',
  'credit_id': '59a8b904c3a3683c7a02381c',
  'gender': 0,
  'id': 1093707,
  'name': 'Benjamin Blankenship',
  'order': 36,
  'profile_path': '/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg'},
 {'cast_id': 156,
  'character': 'DJ',
  'credit_id': '59a8b953c3a36876710081c2',
  'gender': 0,
  'id': 1880150,
  'name': 'D.J. Hapa',
  'order': 37,
  'profile_path': None},
 {'cast_id': 140,
  'character': 'DJ',
  'credit_id': '58eee68c92514142020018f0',
  'gender': 0,
  'id': 224092,
  'name': 'T-Pain',
  'order': 38,
  'profile_path': None},
 {'cast_id': 157,
  'character': 'Drone Tech',
  'credit_id': '59a8b98892514157ee01f2d9',
  'gender': 2,
  'id': 54792,
  'name': 'Brian Mahoney',
  'order': 39,
  'profile_path': '/v6pTsqgOHE5TldFV63Kr44idQNe.jpg'},
 {'cast_id': 131,
  'character': 'Jasmine',
  'credit_id': '56417c7b92514128a90018fb',
  'gender': 1,
  'id': 1128522,
  'name': 'Brittney Alger',
  'order': 40,
  'profile_path': '/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg'},
 {'cast_id': 158,
  'character': 'Mando',
  'credit_id': '59a8b9ad92514157ab020902',
  'gender': 0,
  'id': 1451616,
  'name': 'Romeo Santos',
  'order': 41,
  'profile_path': '/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg'},
 {'cast_id': 159,
  'character': 'Advisor',
  'credit_id': '59a8b9ca925141579d020ab6',
  'gender': 1,
  'id': 78804,
  'name': 'Jocelin Donahue',
  'order': 42,
  'profile_path': '/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg'},
 {'cast_id': 160,
  'character': 'Field Reporter',
  'credit_id': '59a8b9da9251415808021296',
  'gender': 0,
  'id': 1880151,
  'name': 'Stephanie Langston',
  'order': 43,
  'profile_path': None},
 {'cast_id': 161,
  'character': 'Cop',
  'credit_id': '59a8b9f192514157a5020874',
  'gender': 0,
  'id': 1448173,
  'name': 'Jorge-Luis Pallo',
  'order': 44,
  'profile_path': '/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg'},
 {'cast_id': 143,
  'character': 'Leo (uncredited / archive)',
  'credit_id': '58eee6b8925141423500180f',
  'gender': 2,
  'id': 96321,
  'name': 'Tego Calder√≥n',
  'order': 45,
  'profile_path': '/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg'},
 {'cast_id': 142,
  'character': 'Neela (uncredited / archive)',
  'credit_id': '58eee6ab92514141ff001971',
  'gender': 1,
  'id': 116277,
  'name': 'Nathalie Kelley',
  'order': 46,
  'profile_path': '/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg'},
 {'cast_id': 29,
  'character': 'Twinkie (uncredited)',
  'credit_id': '5431e03e0e0a265872002bf2',
  'gender': 0,
  'id': 58197,
  'name': 'Shad Moss',
  'order': 47,
  'profile_path': '/A1rHY9B5R9cIQshClcJxBYINg1m.jpg'},
 {'cast_id': 144,
  'character': 'Santos (uncredited / archive)',
  'credit_id': '58eee6c492514141f70019b8',
  'gender': 0,
  'id': 90634,
  'name': 'Don Omar',
  'order': 48,
  'profile_path': '/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg'},
 {'cast_id': 141,
  'character': 'Race Wars Racer (uncredited)',
  'credit_id': '58eee698c3a36826510017dc',
  'gender': 0,
  'id': 1563213,
  'name': 'Klement Tinaj',
  'order': 49,
  'profile_path': None},
 {'cast_id': 139,
  'character': "Brian O'Conner (uncredited)",
  'credit_id': '58eee621c3a368265e001729',
  'gender': 0,
  'id': 1795034,
  'name': 'Caleb Walker',
  'order': 50,
  'profile_path': None},
 {'cast_id': 45,
  'character': "Brian O'Connor (uncredited)",
  'credit_id': '5589e3fd925141569c00003e',
  'gender': 2,
  'id': 1480862,
  'name': 'Cody Walker',
  'order': 51,
  'profile_path': '/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg'}]

In [24]:
for i in df2_max['cast'][0]:
    if i["gender"] == 2 :
        print(f'{i["gender"]}:{i["name"]}')

2:Vin Diesel
2:Paul Walker
2:Dwayne Johnson
2:Tyrese Gibson
2:Ludacris
2:Djimon Hounsou
2:Tony Jaa
2:Kurt Russell
2:Jason Statham
2:Sung Kang
2:Lucas Black
2:Noel Gugliemi
2:John Brotherton
2:Luke Evans
2:Ali Fazal
2:Gentry White
2:Steve Coulter
2:Brian Mahoney
2:Tego Calder√≥n
2:Cody Walker

# Q2

In [27]:
df1['roi']=(df1['profit']/df1['budget'])*100
df2_roi=df1[df1['roi']!=np.inf]
df2_roi.groupby('original_language',as_index=False)['roi'].mean().sort_values('roi',ascending=False)

   original_language           roi
15                ko  3.817941e+07
4                 en  5.439874e+05
3                 el  5.198013e+03
29                tr  9.660000e+02
9                 he  4.562925e+02
28                te  4.400768e+02
2                 de  4.349067e+02
32                zh  4.084563e+02
6                 fa  4.000000e+02
21                pl  3.958170e+02
5                 es  3.794217e+02
16                ml  3.708333e+02
30                ur  3.506738e+02
10                hi  2.713313e+02
27                ta  2.155159e+02
17                mr  1.933333e+02
1                 da  1.913964e+02
14                ja  1.858405e+02
0                 cn  1.738661e+02
8                 fr  1.705117e+02
24                ru  1.687776e+02
20                no  1.480828e+02
26                sv  1.148238e+02
13                it  7.715555e+01
19                nl  3.396170e+01
18                nb  1.884794e+01
22                pt  5.123906e+00
7                 fi -3.031924e+01
12                id -4.161758e+01
23                ro -4.961802e+01
31                vi -5.084615e+01
11                hu -8.716555e+01
25                sr -9.996040e+01

 korean language has the highest ROI

# Q3

In [34]:
df2_genre=df1[~df1['genres'].isna()].reset_index(drop=True)

In [36]:
df2_genre

Empty DataFrame
Columns: [id, belongs_to_collection, budget, genres, homepage, imdb_id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, runtime, spoken_languages, status, tagline, title, Keywords, cast, crew, revenue, profit, roi]
Index: []

[0 rows x 25 columns]

In [30]:
list_genre=[]

for i in range(len(df2_genre)):
    for j in df2_genre['genres'].iloc[i]:
        print(j)
        list_genre.append(j['name'])

In [31]:
uniques_genres=list(set(list_genre))

In [32]:
pd.Series(uniques_genres)

Series([], dtype: object)

In [ ]:
pd.DataFrame(uniques_genres,columns=['Genres'])

# Q4

In [40]:
sample_dict=df2_crew['crew'].iloc[1]
df2_crew=df1[df1['crew'].notna()]
df2_crew

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,roi
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,NaN,NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,NaN,NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588
2,3,NaN,3300000,NaN,http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,296.727273
3,4,NaN,1200000,NaN,http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,1233.333333
4,5,NaN,0,NaN,NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,NaN,NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,1596687,inf
2996,2997,NaN,0,NaN,NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,180590,inf
2997,2998,NaN,65000000,NaN,NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,24456761,37.625786
2998,2999,NaN,42000000,NaN,http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,129963386,309.436633
2999,3000,NaN,35000000,NaN,http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,47087155,134.534729

In [41]:
sample_dict

[{'credit_id': '52fe43fe9251416c7502563d',
  'department': 'Directing',
  'gender': 2,
  'id': 1201,
  'job': 'Director',
  'name': 'Garry Marshall',
  'profile_path': '/kx77E8p5rnEmKxIhFT0qWCEMEik.jpg'},
 {'credit_id': '52fe43fe9251416c75025667',
  'department': 'Camera',
  'gender': 2,
  'id': 1214,
  'job': 'Director of Photography',
  'name': 'Charles Minsky',
  'profile_path': None},
 {'credit_id': '52fe43fe9251416c75025661',
  'department': 'Sound',
  'gender': 2,
  'id': 4500,
  'job': 'Original Music Composer',
  'name': 'John Debney',
  'profile_path': '/hTrlvZlDXQk49nfc2BM9sjKfJv.jpg'},
 {'credit_id': '52fe43fe9251416c7502564f',
  'department': 'Production',
  'gender': 1,
  'id': 8851,
  'job': 'Producer',
  'name': 'Whitney Houston',
  'profile_path': '/69ouDnXnmklYPr4sMJXWKYz81AL.jpg'},
 {'credit_id': '52fe43fe9251416c7502566d',
  'department': 'Editing',
  'gender': 0,
  'id': 12970,
  'job': 'Editor',
  'name': 'Bruce Green',
  'profile_path': '/yplxWPVgwK1b33AjvbhM9mWX2Aw.jpg'},
 {'credit_id': '52fe43fe9251416c75025655',
  'department': 'Production',
  'gender': 2,
  'id': 38415,
  'job': 'Producer',
  'name': 'Mario Iscovich',
  'profile_path': None},
 {'credit_id': '52fe43fe9251416c7502565b',
  'department': 'Production',
  'gender': 1,
  'id': 38416,
  'job': 'Executive Producer',
  'name': 'Ellen H. Schwartz',
  'profile_path': '/6WInjABr1sAYGXaa5qOvSrsHIqP.jpg'},
 {'credit_id': '52fe43fe9251416c75025649',
  'department': 'Production',
  'gender': 1,
  'id': 59973,
  'job': 'Producer',
  'name': 'Debra Martin Chase',
  'profile_path': None},
 {'credit_id': '52fe43fe9251416c75025643',
  'department': 'Writing',
  'gender': 1,
  'id': 25539,
  'job': 'Screenplay',
  'name': 'Shonda Rhimes',
  'profile_path': '/4c77e347InbTAlw9lGvORpZBHV6.jpg'}]

In [42]:
list_producers=[]

for i in sample_dict:
    if i['job']=='Producer':
        list_producers.append(i['name'])

In [43]:
list_producers

['Whitney Houston', 'Mario Iscovich', 'Debra Martin Chase']

In [44]:
def producers_list(dict_prod):
    list_producers=[]

    for i in dict_prod:
        if i['job']=='Producer':
            list_producers.append(i['name'])

    return list_producers

In [49]:
producers_list(df2_crew['crew'])

TypeError: list indices must be integers or slices, not str

In [50]:
df2_crew['producers_list']=df2_crew['crew'].apply(producers_list)

<ipython-input-50-03817b46aee9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_crew['producers_list']=df2_crew['crew'].apply(producers_list)

In [46]:
def directors_list(dict_prod):
    list_directors=[]

    for i in dict_prod:
        if i['job']=='Director':
            list_directors.append(i['name'])

    return list_directors

In [47]:
df2_crew['directors_list']=df2_crew['crew'].apply(directors_list)

<ipython-input-47-a1e7aed60cba>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_crew['directors_list']=df2_crew['crew'].apply(directors_list)

In [51]:
df2_crew1=df2_crew[['title','producers_list','directors_list','roi']]

In [52]:
df2_crew_roi = df2_crew1[df2_crew1['roi']!=np.inf]

In [53]:
df2_crew_roi.sort_values('roi',ascending=False).reset_index(drop=True).iloc[2:5]

,title,producers_list,directors_list,roi
2,"The Karate Kid, Part II",[Jerry Weintraub],[John G. Avildsen],1.018618e+08
3,Nurse 3-D,[Marc Bienstock],[Douglas Aarniokoski],9.999990e+07
4,From Prada to Nada,[],[Angel Gracia],2.688072e+06

# Q5

In [54]:
df1['cast'].iloc[0]

[{'cast_id': 4,
  'character': 'Lou',
  'credit_id': '52fe4ee7c3a36847f82afae7',
  'gender': 2,
  'id': 52997,
  'name': 'Rob Corddry',
  'order': 0,
  'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'},
 {'cast_id': 5,
  'character': 'Nick',
  'credit_id': '52fe4ee7c3a36847f82afaeb',
  'gender': 2,
  'id': 64342,
  'name': 'Craig Robinson',
  'order': 1,
  'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'},
 {'cast_id': 6,
  'character': 'Jacob',
  'credit_id': '52fe4ee7c3a36847f82afaef',
  'gender': 2,
  'id': 54729,
  'name': 'Clark Duke',
  'order': 2,
  'profile_path': '/oNzK0umwm5Wn0wyEbOy6TVJCSBn.jpg'},
 {'cast_id': 7,
  'character': 'Adam Jr.',
  'credit_id': '52fe4ee7c3a36847f82afaf3',
  'gender': 2,
  'id': 36801,
  'name': 'Adam Scott',
  'order': 3,
  'profile_path': '/5gb65xz8bzd42yjMAl4zwo4cvKw.jpg'},
 {'cast_id': 8,
  'character': 'Hot Tub Repairman',
  'credit_id': '52fe4ee7c3a36847f82afaf7',
  'gender': 2,
  'id': 54812,
  'name': 'Chevy Chase',
  'order': 4,
  'profile_path': '/svjpyYtPwtjvRxX9IZnOmOkhDOt.jpg'},
 {'cast_id': 9,
  'character': 'Jill',
  'credit_id': '52fe4ee7c3a36847f82afafb',
  'gender': 1,
  'id': 94098,
  'name': 'Gillian Jacobs',
  'order': 5,
  'profile_path': '/rBnhe5vhNPnhRUdtYahBWx90fJM.jpg'},
 {'cast_id': 10,
  'character': 'Sophie',
  'credit_id': '52fe4ee7c3a36847f82afaff',
  'gender': 1,
  'id': 1159009,
  'name': 'Bianca Haase',
  'order': 6,
  'profile_path': '/4x3nbtD8q8phAJPmoGWXPvz0iM.jpg'},
 {'cast_id': 11,
  'character': 'Kelly',
  'credit_id': '5524ec51c3a3687df3000dbb',
  'gender': 1,
  'id': 86624,
  'name': 'Collette Wolfe',
  'order': 7,
  'profile_path': '/aSD4h5379b2eEw3bLou9ByLimmq.jpg'},
 {'cast_id': 13,
  'character': 'Brad',
  'credit_id': '5524ec8ec3a3687ded000d72',
  'gender': 2,
  'id': 466505,
  'name': 'Kumail Nanjiani',
  'order': 9,
  'profile_path': '/x4nAztHY72SVciRfxEsbhIVTsIu.jpg'},
 {'cast_id': 14,
  'character': 'Courtney',
  'credit_id': '5524ec9bc3a3687df8000d13',
  'gender': 1,
  'id': 70776,
  'name': 'Kellee Stewart',
  'order': 10,
  'profile_path': '/w3xmsEPmJc1Cf0dQ4aIn8YmlHbk.jpg'},
 {'cast_id': 15,
  'character': 'Terry',
  'credit_id': '5524eca892514171cb008237',
  'gender': 2,
  'id': 347335,
  'name': 'Josh Heald',
  'order': 11,
  'profile_path': '/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg'},
 {'cast_id': 16,
  'character': 'Susan',
  'credit_id': '5524ecb7925141720c001116',
  'gender': 0,
  'id': 1451392,
  'name': 'Gretchen Koerner',
  'order': 12,
  'profile_path': '/muULPexCTJGyJba4yKzxronpD50.jpg'},
 {'cast_id': 17,
  'character': 'Herself',
  'credit_id': '5524ecc3c3a3687ded000d74',
  'gender': 1,
  'id': 98879,
  'name': 'Lisa Loeb',
  'order': 13,
  'profile_path': '/bGqg58ca0bZR38z9HliUMmeNGE.jpg'},
 {'cast_id': 18,
  'character': 'Herself',
  'credit_id': '5524ecd3c3a3687e11000ed3',
  'gender': 1,
  'id': 1394648,
  'name': 'Jessica Williams',
  'order': 14,
  'profile_path': '/A4syKjkcYB92wLEhH0c0hC3BCpz.jpg'},
 {'cast_id': 19,
  'character': 'Himself',
  'credit_id': '5524ece6925141718d001009',
  'gender': 0,
  'id': 1451393,
  'name': 'Bruce Buffer',
  'order': 15,
  'profile_path': None},
 {'cast_id': 20,
  'character': 'Shot Girl',
  'credit_id': '5524ecf5c3a3687e08000dc2',
  'gender': 0,
  'id': 1451394,
  'name': 'Mariana Paola Vicente',
  'order': 16,
  'profile_path': '/ckPllza8624UHWGHCbLShkLxCD1.jpg'},
 {'cast_id': 33,
  'character': 'Choozy Doozy Host',
  'credit_id': '555844da9251412afe0013a9',
  'gender': 2,
  'id': 2224,
  'name': 'Christian Slater',
  'order': 17,
  'profile_path': '/3ElLWjnvchMS6Q4cIQOK8QNAoMG.jpg'},
 {'cast_id': 35,
  'character': 'Gary Winkle',
  'credit_id': '55872027c3a3683853005074',
  'gender': 0,
  'id': 185805,
  'name': 'Jason Jones',
  'order': 18,
  'profile_path': '/aIoCw6vo8AGMdsQRAI5g2t0yJT3.jpg'},
 {'cast_id': 36,
  'character': 'Bridesmaid',
  'credit_id': '55efe971c3a368090c00cd1b',
  'gender': 0,
  'id': 1507448,
  'name': 'Olivia Jordan',
  'order': 19,
  'profile_path': '/szMukAEiIDeasel0lvyaeyKuych.jpg'},
 {'cast_id': 37,
  'character': 'Christine',
  'credit_id': '55efe980c3a36871bf008176',
  'gender': 1,
  'id': 1334091,
  'name': 'Christine Bently',
  'order': 20,
  'profile_path': '/oUZltnGa55OXE52hfyPTfCshuNy.jpg'},
 {'cast_id': 38,
  'character': 'Excited Girl',
  'credit_id': '55efe98e9251413e3201d316',
  'gender': 0,
  'id': 557803,
  'name': 'Stacey Asaro',
  'order': 21,
  'profile_path': '/qTPdlr1dXf3kNdyHuDsgtGC0HCC.jpg'},
 {'cast_id': 64,
  'character': 'Adam (uncredited)',
  'credit_id': '58f2135ac3a3682e95008b91',
  'gender': 2,
  'id': 3036,
  'name': 'John Cusack',
  'order': 22,
  'profile_path': '/uKydQYuZ9TnCzvbQLtj6j98vWAT.jpg'},
 {'cast_id': 65,
  'character': 'J-Bird',
  'credit_id': '59ac0240c3a3682cc802c399',
  'gender': 2,
  'id': 59256,
  'name': 'Adam Herschman',
  'order': 23,
  'profile_path': '/wZMwiuX1DslF6hDS50z9OTN6z1X.jpg'},
 {'cast_id': 66,
  'character': 'Bridesmaid',
  'credit_id': '59ac02cd925141079d02b1b4',
  'gender': 1,
  'id': 129714,
  'name': 'Kisha Sierra',
  'order': 24,
  'profile_path': None}]

In [55]:
df2_cast=df1[df1['cast'].notna()].reset_index(drop=True)

In [56]:
list_actors=[]
for i in range(len(df2_cast)):
    dictionary_list=df2_cast['cast'].iloc[i]
    for j in dictionary_list:
        if j['gender']==2:
            list_actors.append(j['name'])

In [57]:
actors_df=pd.DataFrame(list_actors)

In [58]:
actors_df.value_counts()

Samuel L. Jackson       30
Robert De Niro          30
Morgan Freeman          27
Liam Neeson             25
J.K. Simmons            25
                        ..
James Stephens           1
James Thomas Bligh       1
James Tyler Robinson     1
James Urbaniak           1
√ìscar Ladoire           1
Name: count, Length: 13202, dtype: int64

Samuel L. Jackson       30
Robert De Niro          30
acted in the most number of movies